# -*- coding: utf-8 -*-
"""DIP_Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AHMkzxyYGfeSMk4FQNWASlUC99pavTq1
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("/content/PROFILE.jpeg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)

grayimg = 0.2989*img[:,:,0] + 0.5870*img[:,:,1] + 0.1140*img[:,:,2]
plt.imshow(grayimg, cmap='gray')

threshold = 127
grayimg_new = np.zeros((img.shape[0], img.shape[1]))

for i in range(len(grayimg)):
    for j in range(len(grayimg[i])):
        if(grayimg[i,j] < threshold):
            grayimg_new[i,j] = 0
        else:
            grayimg_new[i,j] = gray[i,j]

plt.imshow(grayimg_new, cmap='gray')

sub_gray = gray - gray_new

plt.imshow(sub_gray, cmap='gray')

