# -*- coding: utf-8 -*-
"""DIPassignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KfC4jIcd7giVHlROSFmt_48Fv1MHCZTj
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread("/content/PROFILE.jpeg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

R, G, B = image[:,:,0], image[:,:,1], image[:,:,2]

redImage = image.copy()
redImage[:,:,1], redImage[:,:,2] = 0, 0
plt.imshow(redImage)

blueImage = image.copy()
blueImage[:,:,0], blueImage[:,:,1] = 0, 0
plt.imshow(blueImage)

greenImage = image.copy()
greenImage[:,:,0], greenImage[:,:,2] = 0, 0
plt.imshow(greenImage)