# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rz9iLUgXoONieU3t9usZm79HKxo9AOll
"""

# Commented out IPython magic to ensure Python compatibility.
import math
import numpy as np
import matplotlib.pyplot as plt
import cv2
# %matplotlib inline
image = cv2.imread(r"/content/drive/MyDrive/PROFILE.jpeg")
grayscaleimage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(grayscaleimage)

plt.imshow(grayscaleimage*2)

plt.imshow(grayscaleimage*0.5)

from google.colab import drive
drive.mount('/content/drive')

