# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rz9iLUgXoONieU3t9usZm79HKxo9AOll
"""

from PIL import Image
import matplotlib.pyplot as plt
import cv2
import numpy as np
img = cv2.imread('/content/drive/MyDrive/PROFILE (1).jpeg', 0)
intensity_count = [0] * 256
height, width = img.shape[:2]
N = height * width
high_contrast = np.zeros(img.shape)
for i in range(0, height):
 for j in range(0, width):
  intensity_count[img[i][j]] += 1
L = 256
intensity_count, total_values_used = np.histogram(img.flatten(), L, [0, L])
pdf_list = np.ceil(intensity_count * (L - 1) / img.size)
cdf_list = pdf_list.cumsum()
for y in range(0, height):
 for x in range(0, width):
  high_contrast[y, x] = cdf_list[img[y, x]]
 # PLOT THE HISTOGRAMS
cv2.imwrite('high_contrast.png', high_contrast)
plt.hist(img.ravel(), 256, [0, 256])
plt.xlabel('Intensity Values')
plt.ylabel('Pixel Count')
plt.show()
plt.hist(high_contrast.ravel(), 256, [0, 256])
plt.xlabel('Intensity Values')
plt.ylabel('Pixel Count')
plt.show()



from google.colab import drive
drive.mount('/content/drive')

