# -*- coding: utf-8 -*-
"""DIPassignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WpKmOfunAnRJAXXMnJqv6MHBclwzX2-u
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("/content/PROFILE.jpeg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)

gray = 0.2989*img[:,:,0] + 0.5870*img[:,:,1] + 0.1140*img[:,:,2]

plt.imshow(gray, cmap='gray')

threshold = 105
flag = np.zeros((img.shape[0], img.shape[1]))

for i in range(len(gray)):
    for j in range(len(gray[i])):
        if(gray[i,j] > threshold):
            bin[i,j] = 1

plt.imshow(flag, cmap='binary')

flag_gray = flag + gray

plt.imshow(flag_gray, cmap='gray')

gray_new = gray + 20

plt.imshow(gray_new, cmap='gray')

